import { notFound, redirect } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RefundDialog } from "@/components/payments/refund-dialog";
import { db } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";
import { can } from "@/lib/permissions";

function date(value: Date) { const [year, month, day] = value.toISOString().slice(0, 10).split("-"); return `${month}/${day}/${year}`; }
function price(value: string) { const [whole, decimals] = value.split("."); return `₹${whole.replace(/\B(?=(\d{3})+(?!\d))/g, ",")}${decimals ? `.${decimals}` : ".00"}`; }

export default async function PaymentDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser();
  if (!can(user.role, "payments:view")) redirect("/dashboard");
  const { id } = await params;
  const payment = await db.payment.findFirst({ where: { id, organizationId: user.organizationId }, include: { member: { select: { name: true, phone: true, email: true } }, subscription: { select: { startDate: true, endDate: true, status: true, amount: true, plan: { select: { name: true } } } }, creator: { select: { name: true } }, adjustments: { select: { id: true, amount: true, status: true, notes: true, createdAt: true } } } });
  if (!payment) notFound();
  return <div className="space-y-6"><div><p className="text-sm text-muted-foreground">Payment details</p><h1 className="text-2xl font-semibold tracking-tight">{payment.receiptNumber}</h1></div><Card><CardHeader><CardTitle>Payment information</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Amount</p><p className="text-2xl font-semibold">{price(payment.amount.toString())}</p></div><div><p className="text-xs text-muted-foreground">Status</p><Badge variant={payment.status === "COMPLETED" ? "success" : payment.status === "REFUNDED" ? "destructive" : "secondary"}>{payment.status}</Badge></div><div><p className="text-xs text-muted-foreground">Method</p><p>{payment.paymentMethod}</p></div><div><p className="text-xs text-muted-foreground">Payment date</p><p>{date(payment.paymentDate)}</p></div><div><p className="text-xs text-muted-foreground">Reference</p><p>{payment.receiptNumber}</p></div><div><p className="text-xs text-muted-foreground">Created by</p><p>{payment.creator?.name ?? "System"}</p></div><div className="sm:col-span-2"><p className="text-xs text-muted-foreground">Notes</p><p>{payment.notes ?? "-"}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Member and subscription</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Member</p><p>{payment.member.name}</p><p className="text-sm text-muted-foreground">{payment.member.phone} · {payment.member.email ?? "No email"}</p></div>{payment.subscription && <><div><p className="text-xs text-muted-foreground">Plan</p><p>{payment.subscription.plan.name}</p></div><div><p className="text-xs text-muted-foreground">Subscription fee</p><p>{price(payment.subscription.amount.toString())}</p></div><div><p className="text-xs text-muted-foreground">Period</p><p>{date(payment.subscription.startDate)} to {date(payment.subscription.endDate)}</p></div></>}</CardContent></Card>{(payment.status === "COMPLETED" || payment.status === "PARTIALLY_REFUNDED") && can(user.role, "payments:refund") && <RefundDialog paymentId={payment.id} amount={payment.amount.toString()} />}{payment.adjustments.length > 0 && <Card><CardHeader><CardTitle>Refund history</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{payment.adjustments.map((adjustment) => <div key={adjustment.id} className="flex justify-between border-b pb-2"><span>{adjustment.notes ?? "Refund"}</span><span>{price(adjustment.amount.toString())} · {date(adjustment.createdAt)}</span></div>)}</CardContent></Card>}</div>;
}
